### ISSUE TITLE
noreport doesn't show progress bar

### ISSUE THREAD

**Issue by nkhoit** [nkhoit/simc-discord#2]
When calling -n, the progress bar doesn't load.
Also, instead of sending a message, it should just edit the previous one with @name right?

@lia978 @kurtmueller42

**Comment by kmz42** [comment]
The goal of the simc_utils class is to remove any dependence on discord so it can be tested separately without having a bot set up. Hence, it just runs a full simulation then returns the string of the output

It's still possible to a progress bar if we pass around a file descriptor but that doesn't happen right now

**Comment by nkhoit** [comment]
hmm okay, I think I can just pass it with an optional argument. So it'll do it if I pass the file descriptor and it'll not do it if I didn't.
